### ISSUE TITLE
For MacTex user

### ISSUE THREAD

**Issue by yinxiaochuan** [linxdcn/TongjiThesis#2]
Change the line 96-102 in tongjithesis.cls as follows  
\setCJKmainfont{STSong}
 \setCJKsansfont{STHeiti}
 \setCJKmonofont{STKaiti}
 \setCJKfamilyfont{song}{STSong}
 \setCJKfamilyfont{hei}{STHeiti}
 \setCJKfamilyfont{fs}{STFangsong}
 \setCJKfamilyfont{kai}{STKaiti}

**Comment by linxdcn** [comment]
@yinxiaochuan Thanks for your suggestion. Your code is added and is commented by default. More details can refer to README
