### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by yinxiaochuan** [linxdcn/TongjiThesis#3]
请问一下，参考文献格式不一样，你知道怎么修改么？学校的标准是[参考文献序号]

**Comment by linxdcn** [comment]
@yinxiaochuan 你把these.tex文件中的tongjibib-lxd改为tongjibib即可

**Comment by yinxiaochuan** [comment]
谢谢~

**Comment by yinxiaochuan** [comment]
并没有效果

**Comment by linxdcn** [comment]
@yinxiaochuan 不好意思，现在手头上没有实验环境。2楼说的不用改。

你试一下看可不可以：

1. 将tongjithesis.cls文件中的

%\bibpunct{（}{）}{，}{a}{}{，}

改为

\bibpunct{[}{]}{，}{s}{}{，}

2.删除

\renewcommand\cite[1] {(\citeauthor{#1},\citeyear{#1}）}
\renewcommand\citeyearpar[1] {（\citeyear{#1}）}

**Comment by yinxiaochuan** [comment]
@linxdcn 搞定了，太感谢了
